services:
  db:
    image: postgres:latest
    container_name: ihhah-postgres
    environment:
      POSTGRES_DB: ihhah-sms
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    networks:
      - ihhah-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: ihhah-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - ihhah-network

networks:
  ihhah-network:
    driver: bridge
